spring:
  application:
    name: spring-db-1-core

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/workspace/utils/h2/test
    username: sa
    password:

  sql:
    init:
      mode: always
